### ISSUE TITLE
Tare command

### ISSUE THREAD

**Issue by Aldaviva** [Aldaviva/webscale#1]
As a WebScale user, I would like to issue a tare command programmatically, so I can zero the reading without physically power-cycling the scale.

There are two ways to tare (zero) the scale:
1. Power cycle the scale, by replugging the USB cable or switching the power switch 1->0->1.
2. Use the official Stamps.com software to send a tare command over USB.

**Comment by niftylettuce** [comment]
@Aldaviva did you ever manage to add this feature in?

**Comment by Aldaviva** [comment]
Hello @niftylettuce, for some reason I never got an email notification for your comment. Sorry for the 3 year delay.

I've been porting this library to .NET today and just figured out how to send the tare command over USB. Using Wireshark and USBPcap, the bytes to write are `0x04 0x01`.

**Comment by Aldaviva** [comment]
Added [`tare()`](https://github.com/Aldaviva/webscale#tare) command to [webscale@0.1.0](https://www.npmjs.com/package/webscale/v/0.1.0), published to npm.
